services:
  grafana:
    container_name: jakson-jmap-panel
    image: grafana/grafana-oss:12.3.1
    user: "0"
    ports:
      - "3000:3000"
    volumes:
      - ./dist:/var/lib/grafana/plugins/jakson-jmap-panel
      - ./provisioning:/etc/grafana/provisioning
    environment:
      GF_LOG_LEVEL: info
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: jakson-jmap-panel
