services:
  grafana:
    user: root
    container_name: 'jakson-jmap-panel'

    build:
      context: .
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-oss}
        grafana_version: ${GRAFANA_VERSION:-12.3.1}
        development: ${DEVELOPMENT:-false}
        anonymous_auth_enabled: ${ANONYMOUS_AUTH_ENABLED:-true}
    ports:
      - 3000:3000/tcp
    volumes:
      - ../dist:/var/lib/grafana/plugins/jakson-jmap-panel
      - ../provisioning:/etc/grafana/provisioning
      - ..:/root/jakson-jmap-panel

    environment:
      NODE_ENV: development
      GF_LOG_FILTERS: plugin.jakson-jmap-panel:debug
      GF_LOG_LEVEL: debug
      GF_DATAPROXY_LOGGING: 1
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: jakson-jmap-panel
